name: CI
on:
  pull_request:
    branches: [main]
    types: [opened, reopened, edited, ready_for_review]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install e .[dev]

      - name: Run pre-commit hooks
        run: |
          pre-commit run --all-files

      - name: Run tests
        run: |
          pytest tests/
