name: CI
on:
  pull_request:
    branches: [main]
    types: [
        edited,
        opened,
        ready_for_review,
        reopened,
        review_requested,
        synchronize,
    ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.13'
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run pre-commit hooks
        run: |
          uv run pre-commit run --all-files

      - name: Run tests
        run: |
          uv run pytest tests/
